{
    "name": "Southern Parts Intelligence",
    "version": "19.0.1.8.1",
    "category": "Inventory/Inventory",
    "summary": "Adds OEM cross references, fitment, specifications, catalog pages, and source tracking to parts.",
    "author": "Southern Equipment Company",
    "website": "https://github.com/Titan-ERP/titan-erp",
    "depends": [
        "product",
        "stock",
        "purchase",
        "website_sale",
        "mail",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/security_defaults.xml",
        "data/catalog_agent_defaults.xml",
        "data/catalog_sync_cron.xml",
        "data/evidence_queue_cron.xml",
        "data/partner_pricelist.xml",
        "data/quality_cron.xml",
        "views/product_template_views.xml",
        "views/parts_intelligence_views.xml",
        "views/catalog_sync_views.xml",
        "views/sparex_sourcing_views.xml",
        "views/catalog_agent_views.xml",
        "views/sparex_discovery_views.xml",
        "views/evidence_queue_views.xml",
        "views/product_quality_views.xml",
        "views/website_product_templates.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "southern_parts_intelligence/static/src/scss/parts_catalog.scss",
        ],
    },
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
