{
    "name": "Southern Accounting Guardrails",
    "version": "19.0.1.2.0",
    "category": "Accounting/Accounting",
    "summary": "Review fields and queues for Shop Boss-backed accounting cleanup.",
    "depends": [
        "account",
        "product",
        "sale",
        "stock",
        "mail",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/revenue_rules.xml",
        "data/ir_cron.xml",
        "views/accounting_policy_views.xml",
        "views/revenue_rule_views.xml",
        "views/daily_control_views.xml",
        "views/account_move_line_views.xml",
        "views/shop_boss_document_views.xml",
        "views/shop_boss_payment_batch_views.xml",
        "views/account_move_views.xml",
        "views/bank_statement_line_views.xml",
        "views/product_accounting_views.xml",
        "views/southern_accounting_menus.xml",
    ],
    "installable": True,
    "application": False,
    "post_init_hook": "post_init_hook",
    "license": "LGPL-3",
}
