{
    "name": "Southern Customer Portal",
    "version": "19.0.1.0.6",
    "category": "Website/Portal",
    "summary": "Customer portal pages for memberships, outstanding repair orders, and invoices.",
    "author": "Southern Equipment Company",
    "depends": [
        "portal",
        "account",
        "repair",
        "mail",
        "purchase",
        "sale_stock",
        "delivery",
        "website_sale",
        "sale_subscription",
        "website_sale_subscription",
        "auth_signup",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/membership_views.xml",
        "views/partner_application_views.xml",
        "views/res_partner_views.xml",
        "views/customer_portal_templates.xml",
    ],
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
