import csv
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

MASTER_PATHS = [
    ROOT / "outputs" / "southern_equipment_master_parts_database_v1" / "master_products.csv",
    ROOT / "odoo_imports" / "product_master" / "import_ready" / "master_products.csv",
]
REVIEW_PATHS = [
    ROOT / "outputs" / "southern_equipment_master_parts_database_v1" / "needs_review.csv",
    ROOT / "odoo_imports" / "product_master" / "review_reports" / "needs_review.csv",
]
SOURCE_PATHS = [
    ROOT / "outputs" / "southern_equipment_master_parts_database_v1" / "web_oem_lookup_sources.csv",
    ROOT / "odoo_imports" / "product_master" / "review_reports" / "web_oem_lookup_sources.csv",
]


OVERRIDES = {
    "JD9080": {
        "Product Name": "Tapered Roller Bearing Cone - JD9080",
        "Product Family": "Bearings",
        "Product Category": "Bearings",
        "Manufacturer": "John Deere",
        "Source Name": "John Deere Shop",
        "Source URL": "https://shop.deere.com/us/product/JD9080%3A-Tapered-Roller-Bearing-Cone/p/JD9080",
        "Evidence": "John Deere lists JD9080 as a tapered roller bearing cone.",
    },
    "AA205DD": {
        "Product Name": "Seed Opener Bearing - 205DD",
        "Product Family": "Bearings",
        "Product Category": "Bearings",
        "Manufacturer": "BCA",
        "Source Name": "MalpasOnline",
        "Source URL": "https://www.malpasonline.co.uk/oem/AA205DD/BCA",
        "Evidence": "AA205DD is listed as a BCA seed opener bearing with bearing reference 205DD.",
    },
    "GRA100RRB": {
        "Product Name": "Ball Insert Bearing - 1 in Bore",
        "Product Family": "Bearings",
        "Product Category": "Bearings",
        "Manufacturer": "Timken",
        "Source Name": "Timken",
        "Source URL": "https://cad.timken.com/item/insert-ball-bearings/fafnir--eccentric-locking-collar-ball-bearings/gra100rrb",
        "Evidence": "Timken lists GRA100RRB as a Fafnir eccentric locking collar ball bearing with 1.0000 in bore.",
    },
    "46436": {
        "Product Name": "Air Filter - WIX 46436",
        "Product Family": "Air Filters",
        "Product Category": "Filters / Air Filters",
        "Manufacturer": "WIX",
        "Source Name": "Wheeler Fleet",
        "Source URL": "https://www.wheelerfleet.com/product/air-filter/797230",
        "Evidence": "Wheeler Fleet lists WIX 46436 as an air filter.",
    },
    "RS3734": {
        "Product Name": "Air Filter - RS3734",
        "Product Family": "Air Filters",
        "Product Category": "Filters / Air Filters",
        "Manufacturer": "Baldwin",
        "Source Name": "NAPA",
        "Source URL": "https://www.napaonline.com/en/p/TWDRS3734",
        "Evidence": "NAPA lists RS3734 as an air cleaner filter element.",
    },
    "PA1681": {
        "Product Name": "Outer Air Filter Element with Fins - PA1681",
        "Product Family": "Air Filters",
        "Product Category": "Filters / Air Filters",
        "Manufacturer": "Baldwin",
        "Source Name": "FinditParts",
        "Source URL": "https://www.finditparts.com/p/pa1681-fn-baldwin-air-flter-65290",
        "Evidence": "Baldwin PA1681-FN is described as an outer air element with fins.",
    },
    "HF35018": {
        "Product Name": "Hydraulic Filter - HF35018",
        "Product Family": "Hydraulic Filters",
        "Product Category": "Filters / Hydraulic Filters",
        "Manufacturer": "Fleetguard",
        "Source Name": "Komatsu",
        "Source URL": "https://www.komatsu.com/en-us/products/parts/filters/hf35018",
        "Evidence": "Komatsu lists HF35018 as a hydraulic filter.",
    },
    "V0521-51940": {
        "Product Name": "Fuel Water Separator Element - V0521-51940",
        "Product Family": "Fuel Water Separators",
        "Product Category": "Filters / Fuel Water Separators",
        "Manufacturer": "Kubota",
        "Source Name": "Messicks",
        "Source URL": "https://www.messicks.com/parts/kubota/v0521-51940",
        "Evidence": "Messicks lists V0521-51940 as a Kubota fuel separator element assembly.",
    },
    "DZ118286": {
        "Product Name": "Engine Oil Filter - DZ118286",
        "Product Family": "Engine Oil Filters",
        "Product Category": "Filters / Engine Oil Filters",
        "Manufacturer": "John Deere",
        "Source Name": "John Deere Shop",
        "Source URL": "https://shop.deere.com/br/pt/product/DZ118286%253A-Filtro-de-%25C3%2593leo-do-Motor/p/DZ118286",
        "Evidence": "John Deere lists DZ118286 as an engine oil filter.",
    },
    "119802-55810": {
        "Product Name": "Fuel Filter - 119802-55810",
        "Product Family": "Fuel Filters",
        "Product Category": "Filters / Fuel Filters",
        "Manufacturer": "Yanmar",
        "Source Name": "Yanmar Shop",
        "Source URL": "https://yanmarshop.com/en-GB/catalog/all/search?_q=119802-55810&_t=a",
        "Evidence": "Yanmar Shop lists 119802-55810 as FILTER,FO in fuel filter diagrams.",
    },
    "194515-24930": {
        "Product Name": "Suction Filter - 194515-24930",
        "Product Family": "Hydraulic Filters",
        "Product Category": "Filters / Hydraulic Filters",
        "Manufacturer": "Yanmar",
        "Source Name": "PartsTree",
        "Source URL": "https://www.partstree.com/models/ex2900-54acc4o-727-cub-cadet-yanmar-ex-series-compact-tractor/oil-strainer-ex2900-90/",
        "Evidence": "PartsTree lists CY-194515-24930 as FILTER, SUCTION.",
    },
    "44X72X10": {
        "Product Name": "Oil Seal - 44 x 72 x 10 mm",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Timken",
        "Source Name": "Timken",
        "Source URL": "https://cad.timken.com/item/seals/oil-seals-metric/44x72x10-rls35-s-1",
        "Evidence": "Timken lists 44X72X10 as a metric oil seal with 44 mm shaft, 72 mm bore, and 10 mm width.",
    },
    "87420952": {
        "Product Name": "Fuel Shutoff Solenoid - 12V",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Case",
        "Source Name": "CNH Store",
        "Source URL": "https://www.mycnhstore.com/us/en/casece/category/electrical/switches/solenoid-valve/p/87420952",
        "Evidence": "CNH lists 87420952 as a 12-volt fuel shutoff solenoid.",
    },
    "3904630": {
        "Product Name": "Fuel Shutoff Solenoid - 12V",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Cummins",
        "Source Name": "Diesel Parts Direct",
        "Source URL": "https://www.dieselpartsdirect.com/3904630",
        "Evidence": "Diesel Parts Direct lists 3904630 as a Cummins solenoid compatible with B-series engines at 12V.",
    },
    "T0070-16324": {
        "Product Name": "Air Cleaner Filter Assembly - T0070-16324",
        "Product Family": "Air Filters",
        "Product Category": "Filters / Air Filters",
        "Manufacturer": "Kubota",
        "Source Name": "Messicks",
        "Source URL": "https://www.messicks.com/parts/kubota/t0070-16324",
        "Evidence": "Messicks lists T0070-16324 as a Kubota complete air cleaner filter assembly.",
    },
    "HNXJBT-02305": {
        "Product Name": "Fuel Filter - HNXJBT-02305",
        "Product Family": "Fuel Filters",
        "Product Category": "Filters / Fuel Filters",
        "Manufacturer": "Hyundai",
        "Source Name": "MagnaSource",
        "Source URL": "https://www.magnasourceinc.com/itemdetail/HNXJBT-02305",
        "Evidence": "MagnaSource lists HNXJBT-02305 / XJBT-02305 as FILTER - FUEL for Hyundai.",
    },
    "6516722": {
        "Product Name": "Hydraulic Oil Filter - 6516722",
        "Product Family": "Hydraulic Filters",
        "Product Category": "Filters / Hydraulic Filters",
        "Manufacturer": "Bobcat",
        "Source Name": "Bobcat",
        "Source URL": "https://shop.bobcat.com/hydraulic-oil-filters-6516722",
        "Evidence": "Bobcat lists 6516722 as a hydraulic oil filter.",
    },
    "57243": {
        "Product Name": "Spin-On Lube Filter - WIX 57243",
        "Product Family": "Engine Oil Filters",
        "Product Category": "Filters / Engine Oil Filters",
        "Manufacturer": "WIX",
        "Source Name": "WIX",
        "Source URL": "https://www2.wixfilters.com/Lookup/PartDetails.aspx?Part=106190",
        "Evidence": "WIX lists 57243 as a spin-on lube filter.",
    },
    "57145": {
        "Product Name": "Spin-On Lube Filter - WIX 57145",
        "Product Family": "Engine Oil Filters",
        "Product Category": "Filters / Engine Oil Filters",
        "Manufacturer": "WIX",
        "Source Name": "FinditParts",
        "Source URL": "https://www.finditparts.com/products/2523626/wix-filters-57145",
        "Evidence": "FinditParts lists WIX 57145 as a spin-on lube filter.",
    },
    "3434465": {
        "Product Name": "Transmission Filter Element - 343-4465",
        "Product Family": "Hydraulic Filters",
        "Product Category": "Filters / Hydraulic Filters",
        "Manufacturer": "Caterpillar",
        "Source Name": "Cat Parts",
        "Source URL": "https://parts.cat.com/en/catcorp/product/343-4465",
        "Evidence": "Cat Parts lists 343-4465 as a transmission element under hydraulic and transmission filters.",
    },
    "3416643": {
        "Product Name": "Hydraulic Filter - 341-6643",
        "Product Family": "Hydraulic Filters",
        "Product Category": "Filters / Hydraulic Filters",
        "Manufacturer": "Caterpillar",
        "Source Name": "SF Filter",
        "Source URL": "https://www.sf-filter.com/en/vergleichsliste/3416643.htm",
        "Evidence": "SF Filter cross-reference lists Caterpillar 3416643 as a hydraulic filter.",
    },
    "B7181": {
        "Product Name": "Lube Spin-On Filter - Baldwin B7181",
        "Product Family": "Engine Oil Filters",
        "Product Category": "Filters / Engine Oil Filters",
        "Manufacturer": "Baldwin",
        "Source Name": "TruckPro",
        "Source URL": "https://www.truckpro.com/p/baldwin-lube-spin-on-b7181/bab7181/",
        "Evidence": "TruckPro lists Baldwin B7181 as a lube spin-on filter.",
    },
    "G1106KRRB": {
        "Product Name": "Ball Insert Bearing - 1-3/8 in Bore",
        "Product Family": "Bearings",
        "Product Category": "Bearings",
        "Manufacturer": "Timken",
        "Source Name": "Timken",
        "Source URL": "https://cad.timken.com/item/fafnir-inserts/fafnir--eccentric-locking-collar-ball-bearings/g1106krrb",
        "Evidence": "Timken lists G1106KRRB as a Fafnir eccentric locking collar ball bearing with 1.3750 in bore.",
    },
    "RA107RRB": {
        "Product Name": "Ball Insert Bearing - 1-7/16 in Bore",
        "Product Family": "Bearings",
        "Product Category": "Bearings",
        "Manufacturer": "Timken",
        "Source Name": "Radwell",
        "Source URL": "https://www.radwell.com/Buy/TIMKEN/TIMKEN/RA107RRB",
        "Evidence": "Radwell lists Timken RA107RRB as an eccentric locking collar ball bearing with 1-7/16 in shaft size.",
    },
    "RA104RRB": {
        "Product Name": "Spherical Ball Bearing - 1-1/4 in Bore",
        "Product Family": "Bearings",
        "Product Category": "Bearings",
        "Manufacturer": "Timken",
        "Source Name": "John Deere Shop",
        "Source URL": "https://shop.deere.com/us/product/A-RA104RRB-I%3A-Spherical-Ball-Bearing/p/A-RA104RRB-I",
        "Evidence": "John Deere lists A-RA104RRB-I as a spherical ball bearing.",
    },
    "CH18562": {
        "Product Name": "Ball Bearing - CH18562",
        "Product Family": "Bearings",
        "Product Category": "Bearings",
        "Manufacturer": "John Deere",
        "Source Name": "John Deere Shop",
        "Source URL": "https://shop.deere.com/us/product/CH18562%3A-Ball-Bearing/p/CH18562",
        "Evidence": "John Deere lists CH18562 as a ball bearing.",
    },
    "LM6704802": {
        "Product Name": "Tapered Roller Bearing Cone - LM67048",
        "Product Family": "Bearings",
        "Product Category": "Bearings",
        "Manufacturer": "Timken",
        "Source Name": "Timken",
        "Source URL": "https://cad.timken.com/item/tapered-roller-bearings---single-cones/tapered-roller-bearings-single-cones-imperial/lm67048",
        "Evidence": "Timken lists LM67048 as a tapered roller bearing single cone.",
    },
    "194464-52190": {
        "Product Name": "PTO Safety Switch - 194464-52190",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Yanmar",
        "Source Name": "BartsParts",
        "Source URL": "https://bartsparts.com/products/yanmar-19446452190/",
        "Evidence": "BartsParts lists Yanmar 194464-52190 as a PTO Safety Switch.",
    },
    "1A8160-52300": {
        "Product Name": "Seat Switch Assembly - 1A8160-52300",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Yanmar",
        "Source Name": "PartsTree",
        "Source URL": "https://www.partstree.com/models/ex3200-54abc4mk727-cub-cadet-yanmar-ex-series-compact-tractor/seat-switch-118/",
        "Evidence": "PartsTree lists CY-1A8160-52300 as SWITCH, SEAT, DELTA, AS, ASSY.",
    },
    "08076-50350": {
        "Product Name": "Komatsu Switch - 08076-50350",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Komatsu",
        "Source Name": "TAOP Parts",
        "Source URL": "https://www.taopparts.com/en/switch/54531-dismantled-komatsu-switch-reference-08076-50350-bulldozer-d155ax-3.html",
        "Evidence": "TAOP Parts lists 08076-50350 as a Komatsu switch.",
    },
    "HA00001310A": {
        "Product Name": "Emergency Switch Assembly - Waterproof",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Hitachi",
        "Source Name": "Varner Parts",
        "Source URL": "https://varnerparts.com/products/emergency-switch-assy-water-proof-ha00001310a",
        "Evidence": "Varner Parts lists HA00001310A as an emergency switch assembly, waterproof.",
    },
    "6742-01-0330": {
        "Product Name": "Solenoid Assembly - 6742-01-0330",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Komatsu",
        "Source Name": "Komatsu",
        "Source URL": "https://www.komatsu.com/en-us/products/parts/engine/6742-01-0330",
        "Evidence": "Komatsu lists 6742-01-0330 as a solenoid assembly.",
    },
    "6356012": {
        "Product Name": "Solenoid Coil - 12V DC",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "HydraForce",
        "Source Name": "Paro",
        "Source URL": "https://paro.nl/library/components/hydraforce/6356012-coil-10-ag-dg-12v-dc",
        "Evidence": "Paro lists HydraForce 6356012 as COIL 10 AG&DG 12V DC with description Solenoid.",
    },
    "T22099": {
        "Product Name": "Plain Bushing - T22099",
        "Product Family": "Hardware",
        "Product Category": "Hardware",
        "Manufacturer": "John Deere",
        "Source Name": "John Deere Shop",
        "Source URL": "https://shop.deere.com/us/product/T22099%3A%2BPlain%2BBushing/p/T22099",
        "Evidence": "John Deere lists T22099 as a plain bushing.",
    },
    "RD537-66770": {
        "Product Name": "Bucket Link Bushing - RD537-66770",
        "Product Family": "Hardware",
        "Product Category": "Hardware",
        "Manufacturer": "Kubota",
        "Source Name": "Messicks",
        "Source URL": "https://www.messicks.com/parts/kubota/rd537-66770",
        "Evidence": "Messicks lists RD537-66770 as a Kubota bush used in bucket link diagrams.",
    },
    "6670682": {
        "Product Name": "Nylon Bearing - 6670682",
        "Product Family": "Bearings",
        "Product Category": "Bearings",
        "Manufacturer": "Bobcat",
        "Source Name": "AllSkidsteers",
        "Source URL": "https://stores.allskidsteers.com/nylon-bearing-for-bobcat-replaces-oem-6670682/",
        "Evidence": "AllSkidsteers lists 6670682 as a nylon bearing for Bobcat.",
    },
    "C5NN3110A": {
        "Product Name": "Lower Spindle Bushing - C5NN3110A",
        "Product Family": "Hardware",
        "Product Category": "Hardware",
        "Manufacturer": "Ford / New Holland",
        "Source Name": "Cross Creek Tractor",
        "Source URL": "https://www.crosscreektractor.com/default.aspx?itemcode=C5NN3110A&page=item+detail",
        "Evidence": "Cross Creek Tractor lists C5NN3110A as a lower spindle bushing for Ford tractors.",
    },
    "1C020-73273": {
        "Product Name": "Thermostat Gasket - 1C020-73273",
        "Product Family": "Engine",
        "Product Category": "Engine / Gaskets",
        "Manufacturer": "Kubota",
        "Source Name": "Coleman Equipment",
        "Source URL": "https://www.colemanequip.com/parts/details/KubotaParts/Kubota-Thermostat-Gasket/1C020-73273/",
        "Evidence": "Coleman Equipment lists 1C020-73273 as a Kubota thermostat gasket.",
    },
    "16221-73270": {
        "Product Name": "Engine Thermostat Gasket - 16221-73270",
        "Product Family": "Engine",
        "Product Category": "Engine / Gaskets",
        "Manufacturer": "Kubota",
        "Source Name": "Messicks",
        "Source URL": "https://www.messicks.com/parts/kubota/16221-73270",
        "Evidence": "Messicks lists 16221-73270 as a Kubota engine thermostat gasket.",
    },
    "129150-49811": {
        "Product Name": "Thermostat Gasket - 129150-49811",
        "Product Family": "Engine",
        "Product Category": "Engine / Gaskets",
        "Manufacturer": "Yanmar",
        "Source Name": "Yanmar Shop",
        "Source URL": "https://yanmarshop.com/en-GB/catalog/all/search/page?_q=129150-49811&_r=F53DCL3GOJSW4Y3INVQXE2LOMUXXGZLBOJRWQL3DMF2GC3DPM52WKL3DGFQWKMZXMZRDCZBZHA2DOODDMFTDMYLBGAYTGOLFHEZTMZDCMM7W6ZTGONSXIPJWGATHG2L2MU6TEMA&_rt=a&_t=p",
        "Evidence": "Yanmar Shop lists 129150-49811 as GASKET, THERMOSTAT.",
    },
    "LVU801280": {
        "Product Name": "Rear Cover Gasket - LVU801280",
        "Product Family": "Engine",
        "Product Category": "Engine / Gaskets",
        "Manufacturer": "John Deere",
        "Source Name": "John Deere Shop",
        "Source URL": "https://shop.deere.com/us/us/product/LVU801280%3A-Rear-Cover-Gasket/p/LVU801280",
        "Evidence": "John Deere lists LVU801280 as a rear cover gasket.",
    },
    "1584153622": {
        "Product Name": "Fuel Injector Gasket - 15841-53622",
        "Product Family": "Engine",
        "Product Category": "Engine / Gaskets",
        "Manufacturer": "Kubota",
        "Source Name": "Diesel Parts Direct",
        "Source URL": "https://www.dieselpartsdirect.com/ku1584153622",
        "Evidence": "Diesel Parts Direct lists 15841-53622 / 1584153622 as a Kubota fuel injector gasket.",
    },
    "EAF9447B": {
        "Product Name": "New Holland Gasket - EAF9447B",
        "Product Family": "Engine",
        "Product Category": "Engine / Gaskets",
        "Manufacturer": "New Holland",
        "Source Name": "New Holland Rochester",
        "Source URL": "https://www.newhollandrochester.com/shop/eaf9447b/",
        "Evidence": "New Holland Rochester lists EAF9447B as a New Holland gasket.",
    },
    "60x95x10": {
        "Product Name": "Oil Seal - 60 x 95 x 10 mm",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "SKF / CR Seals",
        "Source Name": "Motion",
        "Source URL": "https://www.motion.com/products/sku/00769439",
        "Evidence": "Motion lists 60X95X10 as a double lip oil seal with 60 mm shaft, 95 mm OD, and 10 mm width.",
    },
    "C0NN6700A": {
        "Product Name": "Front Crankshaft Oil Seal - C0NN6700A",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Ford / New Holland",
        "Source Name": "Reliable Aftermarket Parts",
        "Source URL": "https://www.reliableaftermarketparts.com/en-au/products/c0nn6700a-front-crankshaft-seal",
        "Evidence": "Reliable Aftermarket Parts lists C0NN6700A as a front crankshaft seal for Ford/New Holland tractors.",
    },
    "D9NN7R510BA": {
        "Product Name": "Input Shaft Oil Seal - D9NN7R510BA",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Ford / New Holland",
        "Source Name": "Cross Creek Tractor",
        "Source URL": "https://www.crosscreektractor.com/default.aspx?itemcode=D9NN7R510BA&page=item+detail",
        "Evidence": "Cross Creek Tractor lists D9NN7R510BA as an input shaft oil seal with transmission PTO.",
    },
    "9x4578": {
        "Product Name": "Track Roller Frame Seal - 225 mm ID",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Caterpillar",
        "Source Name": "Cat Parts",
        "Source URL": "https://parts.cat.com/en/catcorp/9X-4578",
        "Evidence": "Cat Parts lists 9X-4578 as a 225 mm inner diameter track roller frame seal.",
    },
    "2002258": {
        "Product Name": "Hydraulic Filter - 2002258",
        "Product Family": "Hydraulic Filters",
        "Product Category": "Filters / Hydraulic Filters",
        "Manufacturer": "Cub Cadet / MTD",
        "Source Name": "Cub Cadet Canada",
        "Source URL": "https://www.cubcadet.ca/en/all-parts/filter-hydraulic/2002258.html",
        "Evidence": "Cub Cadet lists 2002258 as FILTER HYDRAULIC.",
    },
    "1081153": {
        "Product Name": "Hydraulic/Transmission Oil Filter - 108-1153",
        "Product Family": "Hydraulic Filters",
        "Product Category": "Filters / Hydraulic Filters",
        "Manufacturer": "Caterpillar",
        "Source Name": "Cat Parts",
        "Source URL": "https://parts.cat.com/en/catcorp/product/108-1153",
        "Evidence": "Cat Parts lists 108-1153 as a hydraulic/transmission oil filter.",
    },
    "RS3542": {
        "Product Name": "Outer Air Filter Element - Baldwin RS3542",
        "Product Family": "Air Filters",
        "Product Category": "Filters / Air Filters",
        "Manufacturer": "Baldwin",
        "Source Name": "Baldwin Filters R Us",
        "Source URL": "https://www.baldwinfiltersrus.com/baldwin-rs3542-outer-air-element-filter.html",
        "Evidence": "Baldwin Filters R Us lists RS3542 as an outer air element filter.",
    },
    "6736515142": {
        "Product Name": "Engine Oil Filter - 6735-51-5142",
        "Product Family": "Engine Oil Filters",
        "Product Category": "Filters / Engine Oil Filters",
        "Manufacturer": "Komatsu",
        "Source Name": "Komatsu",
        "Source URL": "https://www.komatsu.com/en-us/products/parts/filters/6735-51-5142",
        "Evidence": "Komatsu lists 6735-51-5142 as an engine oil filter.",
    },
    "6V8105": {
        "Product Name": "Self-Aligning Spherical Plain Bearing - 6V-8105",
        "Product Family": "Bearings",
        "Product Category": "Bearings",
        "Manufacturer": "Caterpillar",
        "Source Name": "Cat Parts",
        "Source URL": "https://parts.cat.com/en/catcorp/6V-8105",
        "Evidence": "Cat Parts lists 6V-8105 as a self-aligning spherical plain bearing.",
    },
    "JD9118": {
        "Product Name": "Tapered Roller Bearing Cup - JD9118",
        "Product Family": "Bearings",
        "Product Category": "Bearings",
        "Manufacturer": "John Deere",
        "Source Name": "John Deere Shop",
        "Source URL": "https://shop.deere.com/us/product/JD9118%3A-Bearing-Cup/p/JD9118",
        "Evidence": "John Deere lists JD9118 as a tapered roller bearing cup.",
    },
    "RA108RR6": {
        "Product Name": "Ball Insert Bearing - 1-1/2 in Bore",
        "Product Family": "Bearings",
        "Product Category": "Bearings",
        "Manufacturer": "Timken",
        "Source Name": "Timken",
        "Source URL": "https://cad.timken.com/item/insert-ball-bearings/fafnir--eccentric-locking-collar-ball-bearings/ra108rrb",
        "Evidence": "Timken lists RA108RRB as an eccentric locking collar ball bearing with 1.5 in bore; source supports same RA108RR family.",
    },
    "2H3712": {
        "Product Name": "Ball Bearing - 40 mm ID",
        "Product Family": "Bearings",
        "Product Category": "Bearings",
        "Manufacturer": "Caterpillar",
        "Source Name": "Cat Parts",
        "Source URL": "https://parts.cat.com/en/catcorp/product/2H-3712",
        "Evidence": "Cat Parts lists 2H-3712 as a 40 mm internal diameter ball bearing.",
    },
    "V6001106006": {
        "Product Name": "Ball Bearing - V6001106006",
        "Product Family": "Bearings",
        "Product Category": "Bearings",
        "Manufacturer": "Bad Boy",
        "Source Name": "Bad Boy Lawn Mower Parts",
        "Source URL": "https://www.badboylawnmowerparts.com/V6001106006-Bad-Boy-BEARING-BALL-p/v6001106006.htm",
        "Evidence": "Bad Boy Lawn Mower Parts lists V6001106006 as BEARING, BALL.",
    },
    "1805475": {
        "Product Name": "Secondary Air Filter Element - 180-5475",
        "Product Family": "Air Filters",
        "Product Category": "Filters / Air Filters",
        "Manufacturer": "Caterpillar",
        "Source Name": "SunSource",
        "Source URL": "https://www.sun-source.com/Product/P610489-donaldson",
        "Evidence": "SunSource lists CATERPILLAR 1805475 with Donaldson P610489 as an air filter, and identifies the type as safety.",
    },
    "FTC5340000A3": {
        "Product Name": "Emergency Lamp Switch - FTC5340000A3",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Bad Boy / TYM",
        "Source Name": "Power Mower Sales",
        "Source URL": "https://powermowersales.com/badboymowers-ftc5340000a3",
        "Evidence": "Power Mower Sales lists FTC5340000A3 as an emergency lamp switch.",
    },
    "4303812": {
        "Product Name": "Solenoid Valve Coil - 12V DC",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "HydraForce",
        "Source Name": "Summit Hydraulics",
        "Source URL": "https://summit-hydraulics.com/product/hydraforce-4303812-solenoid-valve-coil-metri-pack-150-connector-zener-diode-12v-dc-08-series/",
        "Evidence": "Summit Hydraulics lists 4303812 as a HydraForce solenoid valve coil, 12V DC.",
    },
    "1E152-60011": {
        "Product Name": "Diesel Shutoff Solenoid - 12V",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Kubota",
        "Source Name": "YearnParts",
        "Source URL": "https://www.yearnparts.com/12v-shutoff-solenoid-valve-1e152-60011-1e15260011-for-kubota-g2160-b1700d-b2100d-m8200-m9000.html",
        "Evidence": "YearnParts lists 1E152-60011 as a 12V shutoff solenoid valve for Kubota applications.",
    },
    "E6820-60011": {
        "Product Name": "Engine Stop Solenoid - E6820-60011",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Kioti",
        "Source Name": "Nolt's Power Equipment",
        "Source URL": "https://parts.noltspower.com/product/kioti-engine-stop-solenoid-3/",
        "Evidence": "Nolt's Power Equipment lists E6820-60011 as a replaced Kioti engine stop solenoid.",
    },
    "6746-11-4260": {
        "Product Name": "Engine Gasket - 6746-11-4260",
        "Product Family": "Engine",
        "Product Category": "Engine / Gaskets",
        "Manufacturer": "Komatsu",
        "Source Name": "Komatsu",
        "Source URL": "https://www.komatsu.com/en-us/products/parts/engine/6746-11-4260",
        "Evidence": "Komatsu lists 6746-11-4260 under Engine as Gasket.",
    },
    "8n4225": {
        "Product Name": "Rear Axle Shaft Gasket - 8N4225",
        "Product Family": "Driveline",
        "Product Category": "Driveline",
        "Manufacturer": "Ford / New Holland",
        "Source Name": "All States Ag Parts",
        "Source URL": "https://www.fastline.com/rear-axles-differentials-brakes/part-detail/rear-axle-differential-brake-sn-109580-for-ford/75e5f7e9-e5ca-4895-9de1-8ee314269a08",
        "Evidence": "All States Ag Parts lists 8N4225 as a rear axle shaft gasket for Ford 8N.",
    },
    "15522-12350": {
        "Product Name": "Exhaust Manifold Gasket - 15522-12350",
        "Product Family": "Engine",
        "Product Category": "Engine / Gaskets",
        "Manufacturer": "Kubota",
        "Source Name": "Coleman Equipment",
        "Source URL": "https://www.colemanequip.com/parts/details/KubotaParts/Kubota-Exhaust-Manifold-Gasket/15522-12350/",
        "Evidence": "Coleman Equipment lists 15522-12350 as a Kubota exhaust manifold gasket.",
    },
    "6131-11-5170": {
        "Product Name": "Turbo Gasket - 6131-11-5170",
        "Product Family": "Engine",
        "Product Category": "Engine / Gaskets",
        "Manufacturer": "Komatsu",
        "Source Name": "MJ Gasket",
        "Source URL": "https://www.mjgasket.com/product/6131-11-5170-gasket-for-komatsu/",
        "Evidence": "MJ Gasket lists 6131-11-5170 as a Komatsu turbo gasket.",
    },
    "T22097": {
        "Product Name": "Load Sensing Bushing - T22097",
        "Product Family": "Hardware",
        "Product Category": "Hardware",
        "Manufacturer": "John Deere",
        "Source Name": "John Deere Shop",
        "Source URL": "https://shop.deere.com/us/product/T22097%3A-Bushing/p/T22097",
        "Evidence": "John Deere lists T22097 as a load sensing bushing.",
    },
    "P45502": {
        "Product Name": "Bearing Housing - P45502",
        "Product Family": "Bearings",
        "Product Category": "Bearings",
        "Manufacturer": "John Deere",
        "Source Name": "Agrokom",
        "Source URL": "https://sklep-rolnicze.eu/oprawa-lozyska-walek-30mm-john-deere%2C3%2C75302%2C53284",
        "Evidence": "Agrokom lists P45502.01 as a John Deere bearing housing.",
    },
    "707-98-22850": {
        "Product Name": "Angle Cylinder Seal Kit - 707-98-22850",
        "Product Family": "Hydraulic Seal Kits",
        "Product Category": "Seals / Hydraulic Seal Kits",
        "Manufacturer": "Komatsu",
        "Source Name": "Reliable Aftermarket Parts",
        "Source URL": "https://www.reliableaftermarketparts.com/en-au/products/707-98-22850-angle-cylinder-seal-kit-fits-komatsu-d31ex-21",
        "Evidence": "Reliable Aftermarket Parts lists 707-98-22850 as an angle cylinder seal kit for Komatsu crawler dozers.",
    },
    "707-99-58350": {
        "Product Name": "Arm Cylinder Seal Kit - 707-99-58350",
        "Product Family": "Hydraulic Seal Kits",
        "Product Category": "Seals / Hydraulic Seal Kits",
        "Manufacturer": "Komatsu",
        "Source Name": "Reliable Aftermarket Parts",
        "Source URL": "https://www.reliableaftermarketparts.com/products/707-99-58350-cylinder-seal-kit-for-komatsu-excavator-arm-pc220-6-pc230-6",
        "Evidence": "Reliable Aftermarket Parts lists 707-99-58350 as a Komatsu excavator arm cylinder seal kit.",
    },
    "707-99-58080": {
        "Product Name": "Boom Cylinder Seal Kit - 707-99-58080",
        "Product Family": "Hydraulic Seal Kits",
        "Product Category": "Seals / Hydraulic Seal Kits",
        "Manufacturer": "Komatsu",
        "Source Name": "Reliable Aftermarket Parts",
        "Source URL": "https://www.reliableaftermarketparts.com/products/707-99-58080-boom-cylinder-seal-kit-fits-komatsu-pc300-7-pc300lc-7-pc308uslc-3",
        "Evidence": "Reliable Aftermarket Parts lists 707-99-58080 as a Komatsu boom cylinder seal kit.",
    },
    "C5NN3C615A": {
        "Product Name": "Steering Sector Shaft Seal - C5NN3C615A",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Ford / New Holland",
        "Source Name": "Broken Tractor",
        "Source URL": "https://www.brokentractor.com/p/ford-tractor-sector-shaft-seal-for-600-800-2000-3000-3600-4000su-4600su-c5nn3c615a/",
        "Evidence": "Broken Tractor lists C5NN3C615A as a Ford tractor steering sector shaft seal.",
    },
    "E5NN6701BA": {
        "Product Name": "Rear Crankshaft Seal - E5NN6701BA",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Ford / New Holland",
        "Source Name": "TractorPoint",
        "Source URL": "https://tractorpoint.com/cgi-bin/parts/pr_detail_new.pl?item_number=A-E5NN6701BA",
        "Evidence": "TractorPoint lists A-E5NN6701BA as a Ford/New Holland rear crankshaft seal.",
    },
    "C9NN4N109A": {
        "Product Name": "Inner Rear Axle Seal - C9NN4N109A",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Ford / New Holland",
        "Source Name": "Reliable Aftermarket Parts",
        "Source URL": "https://www.reliableaftermarketparts.com/products/fits-new-holland-seal-part-81823109",
        "Evidence": "Reliable Aftermarket Parts lists C9NN4N109A as an inner rear axle seal cross-reference.",
    },
    "9R2505": {
        "Product Name": "Tapered Ring Seal - 9R-2505",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Caterpillar",
        "Source Name": "Cat Parts",
        "Source URL": "https://parts.cat.com/en/catcorp/product/9R-2505",
        "Evidence": "Cat Parts lists 9R-2505 as a tapered section ring seal for rear axle.",
    },
    "9R2496": {
        "Product Name": "Seal Ring - 9R-2496",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Caterpillar",
        "Source Name": "Propel Parts",
        "Source URL": "https://propelparts.us/caterpillar-equipment-seal-9r2496.html",
        "Evidence": "Propel Parts lists 9R2496 as a Caterpillar seal ring replacement.",
    },
    "8G4945": {
        "Product Name": "Hydraulic Cylinder U-Seal - 8G-4945",
        "Product Family": "Hydraulic Seals",
        "Product Category": "Seals / Hydraulic Seals",
        "Manufacturer": "Caterpillar",
        "Source Name": "Cat Parts",
        "Source URL": "https://parts.cat.com/it/catcorp/product/8G-4945",
        "Evidence": "Cat Parts lists 8G-4945 as a U-seal used between hydraulic cylinder and shaft.",
    },
    "1001200812": {
        "Product Name": "Platform Control Cable - 1001200812",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "JLG",
        "Source Name": "BHE Lift Parts",
        "Source URL": "https://bheliftparts.com/products/1001200812-cable-platform-control-1932r-jlg",
        "Evidence": "BHE Lift Parts lists 1001200812 as a JLG cable, platform control.",
    },
    "120-106131": {
        "Product Name": "Brake Solenoid - 120-106131",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "White-Rodgers",
        "Source Name": "Home Depot Repair Parts",
        "Source URL": "https://www.appliancerepair.homedepot.com/PartDetail/Brake-Solenoid/120-106131/2979681",
        "Evidence": "Home Depot Repair Parts lists 120-106131 as a brake solenoid.",
    },
    "128004Gt": {
        "Product Name": "Coupler - 15 Tooth FBA SAE8 - 128004GT",
        "Product Family": "Driveline",
        "Product Category": "Driveline",
        "Manufacturer": "Genie",
        "Source Name": "Zuma Sales",
        "Source URL": "https://zumasales.com/products/coupler-15-tooth-fba-sae8-genie-part-128004gt",
        "Evidence": "Zuma Sales lists 128004GT as a Genie coupler, 15 tooth, FBA, SAE8.",
    },
    "128004GT": {
        "Product Name": "Coupler - 15 Tooth FBA SAE8 - 128004GT",
        "Product Family": "Driveline",
        "Product Category": "Driveline",
        "Manufacturer": "Genie",
        "Source Name": "Zuma Sales",
        "Source URL": "https://zumasales.com/products/coupler-15-tooth-fba-sae8-genie-part-128004gt",
        "Evidence": "Zuma Sales lists 128004GT as a Genie coupler, 15 tooth, FBA, SAE8.",
    },
    "422HC": {
        "Product Name": "Rotary Cutter Blade CCW - 422HC",
        "Product Family": "Driveline",
        "Product Category": "Driveline",
        "Manufacturer": "A&I Products / Howse",
        "Source Name": "Farm Parts Store",
        "Source URL": "https://farmpartsstore.com/rotary-cutter-c-clock-wise-blade-422hc/",
        "Evidence": "Farm Parts Store lists 422HC as a Howse rotary cutter CCW blade.",
    },
    "Ah149194 Seal Kit": {
        "Product Name": "Hydraulic Cylinder Seal Kit - AH149194",
        "Product Family": "Hydraulic Seal Kits",
        "Product Category": "Seals / Hydraulic Seal Kits",
        "Manufacturer": "John Deere",
        "Source Name": "Reliable Aftermarket Parts",
        "Source URL": "https://www.reliableaftermarketparts.com/products/fits-john-deere-ah149194-hydraulic-cylinder-seal-kit",
        "Evidence": "Reliable Aftermarket Parts lists AH149194 as a John Deere hydraulic cylinder seal kit.",
    },
    "AH149194": {
        "Product Name": "Hydraulic Cylinder Seal Kit - AH149194",
        "Product Family": "Hydraulic Seal Kits",
        "Product Category": "Seals / Hydraulic Seal Kits",
        "Manufacturer": "John Deere",
        "Source Name": "Reliable Aftermarket Parts",
        "Source URL": "https://www.reliableaftermarketparts.com/products/fits-john-deere-ah149194-hydraulic-cylinder-seal-kit",
        "Evidence": "Reliable Aftermarket Parts lists AH149194 as a John Deere hydraulic cylinder seal kit.",
    },
    "Ah212088 Seal Kit": {
        "Product Name": "Hydraulic Cylinder Seal Kit - AH212088",
        "Product Family": "Hydraulic Seal Kits",
        "Product Category": "Seals / Hydraulic Seal Kits",
        "Manufacturer": "John Deere",
        "Source Name": "GreenPartStore",
        "Source URL": "https://www.greenpartstore.com/john-deere-hydraulic-cylinder-kit-ah212088.html",
        "Evidence": "GreenPartStore lists AH212088 as a John Deere hydraulic cylinder kit.",
    },
    "AH212088": {
        "Product Name": "Hydraulic Cylinder Seal Kit - AH212088",
        "Product Family": "Hydraulic Seal Kits",
        "Product Category": "Seals / Hydraulic Seal Kits",
        "Manufacturer": "John Deere",
        "Source Name": "GreenPartStore",
        "Source URL": "https://www.greenpartstore.com/john-deere-hydraulic-cylinder-kit-ah212088.html",
        "Evidence": "GreenPartStore lists AH212088 as a John Deere hydraulic cylinder kit.",
    },
    "41450": {
        "Product Name": "Hydraulic Filter - 41450",
        "Product Family": "Hydraulic Filters",
        "Product Category": "Filters / Hydraulic Filters",
        "Manufacturer": "Massey Ferguson",
        "Source Name": "Reliable Aftermarket Parts",
        "Source URL": "https://www.reliableaftermarketparts.com/products/41450-521451m1-hydraulic-filter-fits-massey-ferguson-35-50-65-135uk",
        "Evidence": "Reliable Aftermarket Parts lists 41450 / 521451M1 as a hydraulic filter for Massey Ferguson tractors.",
    },
    "14161010082": {
        "Product Name": "Air Filter Element - 14161010082",
        "Product Family": "Air Filters",
        "Product Category": "Filters / Air Filters",
        "Manufacturer": "Mahindra",
        "Source Name": "Bill's Tractor",
        "Source URL": "https://billstractor.net/mahindra-air-filter-14161010082",
        "Evidence": "Bill's Tractor lists 14161010082 as a Mahindra air filter element.",
    },
    "600-815-8941": {
        "Product Name": "Switch - 600-815-8941",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Komatsu",
        "Source Name": "Komatsu",
        "Source URL": "https://www.komatsu.com/en-us/products/parts/electrical/600-815-8941",
        "Evidence": "Komatsu lists 600-815-8941 under electrical parts as a switch.",
    },
    "HA00000361a": {
        "Product Name": "Safety Switch - HA00000361A",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "McCormick / Bad Boy",
        "Source Name": "Ag-Com",
        "Source URL": "https://www.agcompa.com/product/ha00000361a-safety-switch/",
        "Evidence": "Ag-Com lists HA00000361A as a safety switch.",
    },
    "HA00000361A": {
        "Product Name": "Safety Switch - HA00000361A",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "McCormick / Bad Boy",
        "Source Name": "Ag-Com",
        "Source URL": "https://www.agcompa.com/product/ha00000361a-safety-switch/",
        "Evidence": "Ag-Com lists HA00000361A as a safety switch.",
    },
    "TCD9110000B2": {
        "Product Name": "Switch Assembly - TCD9110000B2",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Bad Boy",
        "Source Name": "Bad Boy Lawn Mower Parts",
        "Source URL": "https://www.badboylawnmowerparts.com/Bad-Boy-Tractors-Switch-AssY-For-Bb4025H-Bb4035H-p/tcd9110000b2.htm",
        "Evidence": "Bad Boy Lawn Mower Parts lists TCD9110000B2 as a switch assembly.",
    },
    "T1850-39010": {
        "Product Name": "Oil Pressure Switch - T1850-39010",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Kubota",
        "Source Name": "Coleman Equipment",
        "Source URL": "https://www.colemanequip.com/parts/details/KubotaParts/Oil-Pressure-Switch/T1850-39010/",
        "Evidence": "Coleman Equipment lists T1850-39010 as a Kubota oil pressure switch.",
    },
    "TZC5110000A3": {
        "Product Name": "Stop Lamp Switch - TZC5110000A3",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "TYM",
        "Source Name": "TYM Tractors UK",
        "Source URL": "https://www.tymtractors.co.uk/part/tzc5110000a3",
        "Evidence": "TYM Tractors UK lists TZC5110000A3 as a stop lamp switch.",
    },
    "tzc5110000a3": {
        "Product Name": "Stop Lamp Switch - TZC5110000A3",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "TYM",
        "Source Name": "TYM Tractors UK",
        "Source URL": "https://www.tymtractors.co.uk/part/tzc5110000a3",
        "Evidence": "TYM Tractors UK lists TZC5110000A3 as a stop lamp switch.",
    },
    "V6041106205": {
        "Product Name": "Ball Bearing - V6041106205",
        "Product Family": "Bearings",
        "Product Category": "Bearings",
        "Manufacturer": "Mahindra / TYM",
        "Source Name": "Mahindra Direct Parts",
        "Source URL": "https://mahindradirectparts.com/collections/transmission/products/mahindra-tractor-bearing-ball-hl1-v6041106205",
        "Evidence": "Mahindra Direct Parts lists V6041106205 as a Mahindra tractor bearing.",
    },
    "88761": {
        "Product Name": "Primary Air Filter - 88761",
        "Product Family": "Air Filters",
        "Product Category": "Filters / Air Filters",
        "Manufacturer": "Carquest",
        "Source Name": "Advance Auto Parts",
        "Source URL": "https://shop.advanceautoparts.com/p/carquest-premium-radial-seal-outer-air-element-88761/10695174-P",
        "Evidence": "Advance Auto Parts lists Carquest 88761 as a premium primary radial seal air filter.",
    },
    "RA012RRB-I": {
        "Product Name": "Spherical Ball Bearing with Collar - 3/4 in - RA012RRB-I",
        "Product Family": "Bearings",
        "Product Category": "Bearings",
        "Manufacturer": "A&I Products",
        "Source Name": "Monroe Tractor",
        "Source URL": "https://www.monroetractor.com/part-details/a-i-products-bearing-3-4-quot/A-RA012RRB-I/",
        "Evidence": "Monroe Tractor lists A-RA012RRB-I as an A&I Products 3/4 inch bearing.",
    },
    "194180-32670": {
        "Product Name": "Front Axle Oil Seal - 79 x 105 x 15 mm - 194180-32670",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Yanmar / Cub Cadet",
        "Source Name": "Traktor",
        "Source URL": "https://traktor.com.pl/en/sealants/1317-sealant-79-x-105-x-15-mm-cub-cadet-ex450-yanmar-ef453tef494t-ae3746g-194180-32670-5-08-101-15.html",
        "Evidence": "Traktor lists 194180-32670 as a front axle / hub reduction seal with 79 x 105 x 15 mm dimensions.",
    },
    "4J8980": {
        "Product Name": "Hydraulic Cylinder Wiper Seal - 4J8980",
        "Product Family": "Hydraulic Seals",
        "Product Category": "Seals / Hydraulic Seals",
        "Manufacturer": "Caterpillar",
        "Source Name": "Allegheny York",
        "Source URL": "https://www.alleghenyyork.com/item/4J8980/CAT-REPLACEMENT-WIPER/",
        "Evidence": "Allegheny York lists 4J8980 as a Cat replacement wiper for hydraulic seal applications.",
    },
    "206-30-55150": {
        "Product Name": "Komatsu Seal - 206-30-55150",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Komatsu",
        "Source Name": "Propel Parts",
        "Source URL": "https://propelparts.us/new4-206-30-55150-Komatsu-Seal.html",
        "Evidence": "Propel Parts lists 206-30-55150 as a Komatsu general seal.",
    },
    "2063055150": {
        "Product Name": "Komatsu Seal - 206-30-55150",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Komatsu",
        "Source Name": "Propel Parts",
        "Source URL": "https://propelparts.us/new4-206-30-55150-Komatsu-Seal.html",
        "Evidence": "Propel Parts lists 206-30-55150 as a Komatsu general seal and replacement 2063055150.",
    },
    "40806": {
        "Product Name": "PTO Shaft Seal - 40806",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Massey Ferguson",
        "Source Name": "Reliable Aftermarket Parts",
        "Source URL": "https://www.reliableaftermarketparts.com/products/195506m1-40806-pto-shaft-seal-fits-massey-ferguson-to35-35-50-65-135-150-165-175",
        "Evidence": "Reliable Aftermarket Parts lists 195506M1 / 40806 as a PTO shaft seal for Massey Ferguson tractors.",
    },
    "195506M1": {
        "Product Name": "PTO Shaft Seal - 195506M1",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Massey Ferguson",
        "Source Name": "Reliable Aftermarket Parts",
        "Source URL": "https://www.reliableaftermarketparts.com/products/195506m1-40806-pto-shaft-seal-fits-massey-ferguson-to35-35-50-65-135-150-165-175",
        "Evidence": "Reliable Aftermarket Parts lists 195506M1 / 40806 as a PTO shaft seal for Massey Ferguson tractors.",
    },
    "65960": {
        "Product Name": "PTO Shaft Seal - S.65960",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Sparex / Ford New Holland",
        "Source Name": "Sparex",
        "Source URL": "https://au.sparex.com/imperial-rotary-shaft-seal-2-15-16-x-3-3-4-x-1-2-65960.html",
        "Evidence": "Sparex lists S.65960 as an imperial rotary shaft seal suitable for Ford/New Holland applications.",
    },
    "937000050": {
        "Product Name": "Komatsu U-Packing - 09370-00050",
        "Product Family": "Hydraulic Seals",
        "Product Category": "Seals / Hydraulic Seals",
        "Manufacturer": "Komatsu",
        "Source Name": "myKomatsu",
        "Source URL": "https://my.komatsu.com.au/shop/idlercushion_5637145280/5637182216_packing_09370-00050",
        "Evidence": "myKomatsu lists 09370-00050 as U-packing for idler cushion applications.",
    },
    "937000060": {
        "Product Name": "Komatsu U-Packing - 09370-00060",
        "Product Family": "Hydraulic Seals",
        "Product Category": "Seals / Hydraulic Seals",
        "Manufacturer": "Komatsu",
        "Source Name": "Aftermarket Express",
        "Source URL": "https://aftermarket.express/komatsu/0937000060",
        "Evidence": "Aftermarket Express lists 09370-00060 / 937000060 as U-packing for Komatsu.",
    },
    "937000090": {
        "Product Name": "Komatsu Hydraulic Cylinder Packing - 09370-00090",
        "Product Family": "Hydraulic Seals",
        "Product Category": "Seals / Hydraulic Seals",
        "Manufacturer": "Komatsu",
        "Source Name": "Propel Parts",
        "Source URL": "https://propelparts.us/new4-09370-00090-Komatsu-Packing.html",
        "Evidence": "Propel Parts lists 09370-00090 / 937000090 as Komatsu hydraulic cylinder packing.",
    },
    "28100-40291-71": {
        "Product Name": "Starter Motor - Toyota Forklift - 28100-40291-71",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Toyota",
        "Source Name": "Lift Parts Warehouse",
        "Source URL": "https://www.liftpartswarehouse.com/product-p/ty28100-40291-71.htm/",
        "Evidence": "Lift Parts Warehouse lists 28100-40291-71 as a replacement starter for Toyota.",
    },
    "1287843C92": {
        "Product Name": "Brake Master Cylinder - 1287843C92",
        "Product Family": "Hardware",
        "Product Category": "Hardware",
        "Manufacturer": "Case IH",
        "Source Name": "Camagris",
        "Source URL": "https://www.cam-agri-parts.fr/fr/emetteur-de-frein-recepteur-de-frein/10581-maitre-cylindre-1287843c92-pour-case-3207213200341.html",
        "Evidence": "Camagris lists 1287843C92 as a brake master cylinder for Case IH tractors.",
    },
    "115163": {
        "Product Name": "Oil Sump Seal Kit - 115163",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "White / Oliver",
        "Source Name": "Reliable Aftermarket Parts",
        "Source URL": "https://www.reliableaftermarketparts.com/en-au/products/s-115163-oil-sump-seal-kit-fits-white-oliver",
        "Evidence": "Reliable Aftermarket Parts lists S.115163 as an oil sump seal kit with references 4031577 and 4600753.",
    },
    "4600753": {
        "Product Name": "Oil Sump Seal Kit - 115163",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "White / Oliver",
        "Source Name": "Reliable Aftermarket Parts",
        "Source URL": "https://www.reliableaftermarketparts.com/en-au/products/s-115163-oil-sump-seal-kit-fits-white-oliver",
        "Evidence": "Reliable Aftermarket Parts lists S.115163 as an oil sump seal kit with references 4031577 and 4600753.",
    },
    "4031577": {
        "Product Name": "Oil Sump Seal Kit - 115163",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "White / Oliver",
        "Source Name": "Reliable Aftermarket Parts",
        "Source URL": "https://www.reliableaftermarketparts.com/en-au/products/s-115163-oil-sump-seal-kit-fits-white-oliver",
        "Evidence": "Reliable Aftermarket Parts lists S.115163 as an oil sump seal kit with references 4031577 and 4600753.",
    },
    "50287": {
        "Product Name": "PTO Seal - 35 x 62 x 10 mm - 50287",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Sparex / Iseki",
        "Source Name": "Sparex",
        "Source URL": "https://ca.sparex.com/metric-rotary-shaft-seal-35-x-62-x-10mm-double-lip-50287.html",
        "Evidence": "Sparex lists S.50287 as a 35 x 62 x 10 mm double lip metric rotary shaft seal.",
    },
    "1700-0950": {
        "Product Name": "Ignition Switch - 1700-0950",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Case IH",
        "Source Name": "Worthington Ag Parts",
        "Source URL": "https://www.worthingtonagparts.com/ignition-switch-to-fit-internationalcaseih-new-aftermarket-wn-a24511",
        "Evidence": "Worthington Ag Parts lists 1700-0950 as a cross-reference for a Case ignition switch.",
    },
    "HA00000067A": {
        "Product Name": "Combination Switch - HA00000067A",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Branson / TYM",
        "Source Name": "Reed & Reed Sales",
        "Source URL": "https://www.reedandreedsales.com/electrical/dash-board-area/combination-switch-ha00000067a",
        "Evidence": "Reed & Reed Sales lists HA00000067A as a combination switch for Branson tractors.",
    },
    "1700000019": {
        "Product Name": "Rotary Switch - 1700000019",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Takeuchi",
        "Source Name": "Takeuchi TB070 Parts Manual",
        "Source URL": "https://www.scribd.com/document/432830217/PARTS-MANUAL-TB070-PL1-101Z5-pdf",
        "Evidence": "Takeuchi parts manual listings show 1700000019 as SWITCH, rotary.",
    },
    "08088-30000": {
        "Product Name": "Switch - 08088-30000",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Komatsu",
        "Source Name": "Komatsu",
        "Source URL": "https://www.komatsu.com/en-us/products/parts/electrical/08088-30000",
        "Evidence": "Komatsu lists 08088-30000 under electrical parts as a switch.",
    },
    "FTC5110000A3": {
        "Product Name": "PTO Connect Switch - FTC5110000A3",
        "Product Family": "Electrical",
        "Product Category": "Electrical",
        "Manufacturer": "Bad Boy",
        "Source Name": "Bad Boy Lawn Mower Parts",
        "Source URL": "https://www.badboylawnmowerparts.com/FTC5110000A3-Bad-Boy-SWITCH-PTO-CONNECT-for-BB40-p/ftc5110000a3.htm",
        "Evidence": "Bad Boy Lawn Mower Parts lists FTC5110000A3 as a PTO connect switch.",
    },
    "126628": {
        "Product Name": "Clamp - 126628",
        "Product Family": "Hardware",
        "Product Category": "Hardware",
        "Manufacturer": "New Holland",
        "Source Name": "Messicks",
        "Source URL": "https://www.messicks.com/parts/new-holland/605025",
        "Evidence": "Messicks lists New Holland 605025 as a clamp replacing 126628.",
    },
    "40352": {
        "Product Name": "Imperial Rotary Shaft Seal - 2-1/4 x 3 x 3/8 in - S.40352",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Sparex",
        "Source Name": "Massey Tractor Parts",
        "Source URL": "https://masseytractorparts.com/products/imperial-rotary-shaft-seal-2-1-4-x-3-x-3-8-s-40352",
        "Evidence": "Massey Tractor Parts lists Sparex S.40352 as an imperial rotary shaft seal, 2-1/4 x 3 x 3/8 in.",
    },
    "40352 57x76x9": {
        "Product Name": "Imperial Rotary Shaft Seal - 57 x 76 x 9 mm - S.40352",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Sparex",
        "Source Name": "Massey Tractor Parts",
        "Source URL": "https://masseytractorparts.com/products/imperial-rotary-shaft-seal-2-1-4-x-3-x-3-8-s-40352",
        "Evidence": "Massey Tractor Parts lists Sparex S.40352 as an imperial rotary shaft seal equivalent to about 57 x 76 x 9 mm.",
    },
    "535209R92": {
        "Product Name": "IPTO Gear Seal Outer - 535209R92",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Case IH / International",
        "Source Name": "Hy-Capacity",
        "Source URL": "https://www.hy-capacity.com/pto-components/ipto/ipto-drive-gears/seals/pid8215/ipto-gear-seal-outer/",
        "Evidence": "Hy-Capacity lists 535209R92 as a cross-reference for 535209 IPTO Gear Seal, Outer.",
    },
    "AH149845": {
        "Product Name": "Hydraulic Cylinder Seal Kit - AH149845",
        "Product Family": "Hydraulic Seal Kits",
        "Product Category": "Seals / Hydraulic Seal Kits",
        "Manufacturer": "John Deere",
        "Source Name": "John Deere Shop",
        "Source URL": "https://shop.deere.com/us/product/AH149845%3A-Kit/p/AH149845",
        "Evidence": "John Deere lists AH149845 as a kit with substitute AH212585 Hydraulic Cylinder Kit.",
    },
    "1934": {
        "Product Name": "O-Ring - 3 x 25 mm - S.1934",
        "Product Family": "Hardware",
        "Product Category": "Hardware",
        "Manufacturer": "Sparex",
        "Source Name": "Sparex",
        "Source URL": "https://fr.sparex.com/joint-torique-3-x-25mm-70-shore-1934.html",
        "Evidence": "Sparex lists S.1934 as a 3 x 25 mm 70 Shore O-ring.",
    },
    "B7487": {
        "Product Name": "Engine Oil Filter - B7487",
        "Product Family": "Engine Oil Filters",
        "Product Category": "Filters / Engine Oil Filters",
        "Manufacturer": "Baldwin",
        "Source Name": "TruckPro",
        "Source URL": "https://www.truckpro.com/p/baldwin-lube-spin-on-B7487/bab7487",
        "Evidence": "TruckPro lists Baldwin B7487 as a lube spin-on filter.",
    },
    "BF1257": {
        "Product Name": "Fuel Water Separator - BF1257",
        "Product Family": "Fuel Water Separators",
        "Product Category": "Filters / Fuel Water Separators",
        "Manufacturer": "Baldwin",
        "Source Name": "NAPA",
        "Source URL": "https://www.napaonline.com/en/p/TWDBF1257",
        "Evidence": "NAPA lists Baldwin BF1257 as a heavy-duty fuel/water separator filter.",
    },
    "F39000354": {
        "Product Name": "Internal Snap Ring - F39000354",
        "Product Family": "Hardware",
        "Product Category": "Hardware",
        "Manufacturer": "John Deere",
        "Source Name": "John Deere Shop",
        "Source URL": "https://shop.deere.com/us/product/F39000354%3A-Internal-Snap-Ring/p/F39000354",
        "Evidence": "John Deere lists F39000354 as an internal snap ring.",
    },
    "3404477M91": {
        "Product Name": "Steering Cylinder Seal Kit - 3404477M91",
        "Product Family": "Hydraulic Seal Kits",
        "Product Category": "Seals / Hydraulic Seal Kits",
        "Manufacturer": "Massey Ferguson",
        "Source Name": "Cross Creek Tractor",
        "Source URL": "https://www.crosscreektractor.com/default.aspx?itemcode=3404477M91&page=item+detail",
        "Evidence": "Cross Creek Tractor lists 3404477M91 as a steering cylinder seal kit for Massey Ferguson tractors.",
    },
    "4135550": {
        "Product Name": "Coolant Water Pump - 4135550",
        "Product Family": "Cooling",
        "Product Category": "Cooling",
        "Manufacturer": "JLG",
        "Source Name": "TMS Equipment Services",
        "Source URL": "https://www.tmsequip.com/tms-parts/jlg-parts-lookup-ordering-system/jlg-parts/jlg-part-4135550-dtz-pump-water-coolant-ea/",
        "Evidence": "TMS Equipment Services lists JLG 4135550 as DTZ-PUMP, WATER COOLANT.",
    },
    "425-815-A320": {
        "Product Name": "Cutting Edge - 425-815-A320",
        "Product Family": "Hardware",
        "Product Category": "Hardware",
        "Manufacturer": "Komatsu",
        "Source Name": "myKomatsu",
        "Source URL": "https://my.komatsu.com.au/shop/edge_5637144802/5637378999_edge_425-815-a320",
        "Evidence": "myKomatsu lists 425-815-A320 as an edge.",
    },
    "140582": {
        "Product Name": "Hydraulic Control Valve Assembly - 140582",
        "Product Family": "Hydraulic Cylinders",
        "Product Category": "Hydraulic",
        "Manufacturer": "Gehl",
        "Source Name": "eBay",
        "Source URL": "https://www.ebay.com/itm/177593457518",
        "Evidence": "Listing describes Gehl SL 4840 skid steer loader hydraulic control valve assembly 140582.",
    },
    "3088577": {
        "Product Name": "Bucket Pin - 3088577",
        "Product Family": "Hardware",
        "Product Category": "Hardware",
        "Manufacturer": "Hitachi / John Deere",
        "Source Name": "19PARTS",
        "Source URL": "https://19parts.com/products/hitachi-pin-3088577",
        "Evidence": "19PARTS lists 3088577 as a Hitachi pin for ZX200 and ZX200-3 applications.",
    },
    "3088580": {
        "Product Name": "Bucket Pin - 3088580",
        "Product Family": "Hardware",
        "Product Category": "Hardware",
        "Manufacturer": "John Deere / Hitachi",
        "Source Name": "John Deere Shop",
        "Source URL": "https://shop.deere.com/us/product/3088580%3A-Pin-Fastener/p/3088580",
        "Evidence": "John Deere lists 3088580 as a pin fastener; heavy-equipment sources also list it as a bucket pin.",
    },
    "594211": {
        "Product Name": "Fuel Filter - 594211",
        "Product Family": "Fuel Filters",
        "Product Category": "Filters / Fuel Filters",
        "Manufacturer": "TVH",
        "Source Name": "BartsParts",
        "Source URL": "https://bartsparts.com/products/tvh-594211/",
        "Evidence": "BartsParts lists TVH 594211 as BRANDSTOF FILTER / fuel filter.",
    },
    "6731-74-5910": {
        "Product Name": "Fuel Injection Seal - 6731-74-5910",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Komatsu",
        "Source Name": "Propel Parts",
        "Source URL": "https://propelparts.us/new4-6731-74-5910-Komatsu-Seal.html",
        "Evidence": "Propel Parts lists 6731-74-5910 as a Komatsu fuel injection seal.",
    },
    "6732-61-6250": {
        "Product Name": "Engine Seal Ring - 6732-61-6250",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Komatsu",
        "Source Name": "myKomatsu",
        "Source URL": "https://my.komatsu.com.au/shop/gasketsealringengine_5637144866/5637475940_seal_6732-61-6250",
        "Evidence": "myKomatsu lists 6732-61-6250 as an engine seal ring with 3.8 x 3.8 x 0.2 cm dimensions.",
    },
    "AT39525": {
        "Product Name": "Internal Oil Seal - AT39525",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "John Deere",
        "Source Name": "John Deere Shop",
        "Source URL": "https://shop.deere.com/us/product/AT39525%3A-Internal-Oil-Seal/p/AT39525",
        "Evidence": "John Deere lists AT39525 as an internal oil seal.",
    },
    "AT124099": {
        "Product Name": "Rod U-Seal - AT124099",
        "Product Family": "Hydraulic Seals",
        "Product Category": "Seals / Hydraulic Seals",
        "Manufacturer": "John Deere / Hitachi",
        "Source Name": "Aztec Hydraulics",
        "Source URL": "https://aztechydraulics.com/products/jd-at124099",
        "Evidence": "Aztec Hydraulics lists John Deere AT124099 as a rod U-seal.",
    },
    "14430-14340": {
        "Product Name": "Komatsu Seal - 144-30-14340",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Komatsu",
        "Source Name": "Zapkomat",
        "Source URL": "https://zapkomat.su/komatsu/PROKLADKA-144-30-14340",
        "Evidence": "Zapkomat lists Komatsu 144-30-14340 / 1443014340 as a seal.",
    },
    "530104R91": {
        "Product Name": "Case IH Seal - 530104R91",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Case IH",
        "Source Name": "Messicks",
        "Source URL": "https://www.messicks.com/parts/case/530104r91",
        "Evidence": "Messicks lists Case 530104R91 as a seal.",
    },
    "735866M1": {
        "Product Name": "Rear Crankshaft Seal - 735866M1",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Massey Ferguson",
        "Source Name": "Cross Creek Tractor",
        "Source URL": "https://crosscreektractor.com/rear-crankshaft-seal-735866m1",
        "Evidence": "Cross Creek Tractor lists 735866M1 as a rear crankshaft seal.",
    },
    "E62GE9": {
        "Product Name": "Transmission Seal - E62GE9",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Ford / New Holland",
        "Source Name": "Sincanli",
        "Source URL": "https://sincanli-testsite.entra.net/en/products/ford-traktor/seals-sealing-products/ford-tractor-seals",
        "Evidence": "Sincanli lists E62GE9 under Ford tractor seals as a transmission seal.",
    },
    "AT210058": {
        "Product Name": "Hydraulic Cylinder Rod - AT210058",
        "Product Family": "Hydraulic Cylinders",
        "Product Category": "Hydraulic / Hydraulic Cylinders",
        "Manufacturer": "John Deere",
        "Source Name": "Construction Equipment Parts",
        "Source URL": "https://ceparts.com/product/rod-at210058/",
        "Evidence": "Construction Equipment Parts lists John Deere AT210058 as a rod.",
    },
    "AT31047": {
        "Product Name": "Final Drive Assembly - AT31047",
        "Product Family": "Driveline",
        "Product Category": "Driveline",
        "Manufacturer": "John Deere",
        "Source Name": "Gulf South Equipment Sales",
        "Source URL": "https://gulfsouthequip.com/product/at31047-john-deere-450b-450c-450d-450e-dozer-final-drive-complete-good-used-outright/",
        "Evidence": "Gulf South Equipment Sales lists AT31047 as a John Deere 450B/450C/450D/450E final drive.",
    },
    "CA40889": {
        "Product Name": "Spider Bearing - CA40889",
        "Product Family": "Bearings",
        "Product Category": "Bearings",
        "Manufacturer": "Blumaq",
        "Source Name": "FinditParts",
        "Source URL": "https://www.finditparts.com/products/17030225/blumaq-ca40889",
        "Evidence": "FinditParts lists Blumaq CA40889 as a drive axle shaft universal joint / spider bearing.",
    },
    "HH1C0-32430": {
        "Product Name": "Engine Oil Filter - HH1C0-32430",
        "Product Family": "Engine Oil Filters",
        "Product Category": "Filters / Engine Oil Filters",
        "Manufacturer": "Kubota",
        "Source Name": "Bahrns",
        "Source URL": "https://www.bahrns.com/kubota-part-cartridge-oil-filter-hh1c0-32430.html",
        "Evidence": "Bahrns lists Kubota HH1C0-32430 as an oil filter cartridge.",
    },
    "HHTA0-59900": {
        "Product Name": "Hydraulic HST Filter - HHTA0-59900",
        "Product Family": "Hydraulic Filters",
        "Product Category": "Filters / Hydraulic Filters",
        "Manufacturer": "Kubota",
        "Source Name": "Coleman Equipment",
        "Source URL": "https://www.colemanequip.com/parts/details/KubotaParts/Kubota-Hydraulic--HST--High-Pressure-Filter/HHTA0-59900/",
        "Evidence": "Coleman Equipment lists Kubota HHTA0-59900 as a hydraulic HST high-pressure filter.",
    },
    "KB1K947-43172": {
        "Product Name": "Fuel Filter - 1K947-43172",
        "Product Family": "Fuel Filters",
        "Product Category": "Filters / Fuel Filters",
        "Manufacturer": "Kubota",
        "Source Name": "The Modern Shop",
        "Source URL": "https://shop.moderngroup.com/1k947-43172-aftermarket-kubota-filter-fuel/",
        "Evidence": "The Modern Shop lists Kubota 1K947-43172 / KB1K947-43172 as a fuel filter.",
    },
    "KB55231-26150": {
        "Product Name": "Air Filter - 55231-26150",
        "Product Family": "Air Filters",
        "Product Category": "Filters / Air Filters",
        "Manufacturer": "Kubota",
        "Source Name": "Trupar Forklift Parts",
        "Source URL": "https://www.truparforkliftparts.com/KUBOTA-55231-26150-FILTER-AIR-p/kb55231-26150.htm",
        "Evidence": "Trupar lists Kubota 55231-26150 / KB55231-26150 as an air filter.",
    },
    "KB59700-26112": {
        "Product Name": "Air Filter - 59700-26112",
        "Product Family": "Air Filters",
        "Product Category": "Filters / Air Filters",
        "Manufacturer": "Kubota",
        "Source Name": "EquipmentShare Parts Store",
        "Source URL": "https://shop.equipmentshare.com/products/kubota-aftermarket-air-filter-tsa-59700-26112",
        "Evidence": "EquipmentShare lists Kubota 59700-26112 / KB59700-26112 as an air filter.",
    },
    "59700-26112": {
        "Product Name": "Air Filter - 59700-26112",
        "Product Family": "Air Filters",
        "Product Category": "Filters / Air Filters",
        "Manufacturer": "Kubota",
        "Source Name": "EquipmentShare Parts Store",
        "Source URL": "https://shop.equipmentshare.com/products/kubota-aftermarket-air-filter-tsa-59700-26112",
        "Evidence": "EquipmentShare lists Kubota 59700-26112 / KB59700-26112 as an air filter.",
    },
    "KBV0631-51880": {
        "Product Name": "Fuel Filter - V0631-51880",
        "Product Family": "Fuel Filters",
        "Product Category": "Filters / Fuel Filters",
        "Manufacturer": "Kubota",
        "Source Name": "The Modern Shop",
        "Source URL": "https://shop.moderngroup.com/v0631-51880-aftermarket-kubota-filter-fuel/",
        "Evidence": "The Modern Shop lists Kubota V0631-51880 / KBV0631-51880 as a fuel filter.",
    },
    "AR92893": {
        "Product Name": "Rear Crankshaft Seal - AR92893",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "John Deere",
        "Source Name": "John Deere Shop",
        "Source URL": "https://shop.deere.com/us/product/A-AR92893%3A-Crankshaft-Rear-Seal/p/A-AR92893",
        "Evidence": "John Deere lists A-AR92893 as a crankshaft rear seal.",
    },
    "MT40210229": {
        "Product Name": "Oil Seal - MT40210229",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "New Holland",
        "Source Name": "Messicks",
        "Source URL": "https://www.messicks.com/parts/new-holland/mt40210229",
        "Evidence": "Messicks lists New Holland MT40210229 as an oil seal.",
    },
    "40807": {
        "Product Name": "Imperial Rotary Shaft Seal - 2-5/16 in x 3-1/8 in x 3/8 in",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Sparex",
        "Source Name": "Sparex",
        "Source URL": "https://us.sparex.com/imperial-double-lip-seal-2-5-16-x-3-1-8-x-3-8-single-lip-40807.html",
        "Evidence": "Sparex lists S.40807 as an imperial rotary shaft seal sized 2-5/16 in x 3-1/8 in x 3/8 in.",
    },
    "65359": {
        "Product Name": "Oil Seal - 141 x 120 x 11.3 mm",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Sparex",
        "Source Name": "Massey Tractor Parts",
        "Source URL": "https://masseytractorparts.com/products/oil-seal-s-65359",
        "Evidence": "Massey Tractor Parts lists Sparex S.65359 as an oil seal and cross-references 83944079, D9NN703BA, D9NN703BB, 83924927, D8NN703AA, 195763M1, and 471829.",
    },
    "167-2323": {
        "Product Name": "Hydraulic Cylinder Rod U-Cup Seal - 167-2323",
        "Product Family": "Hydraulic Seals",
        "Product Category": "Seals / Hydraulic Seals",
        "Manufacturer": "Caterpillar",
        "Source Name": "Cat Parts Store",
        "Source URL": "https://parts.cat.com/en/catcorp/product/167-2323",
        "Evidence": "Cat Parts lists 167-2323 as a cylinder rod U-cup seal.",
    },
    "65870": {
        "Product Name": "Metric Rotary Shaft Seal - 29 x 40 x 8 mm",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Sparex",
        "Source Name": "BartsParts",
        "Source URL": "https://bartsparts.com/products/sparex-65870/",
        "Evidence": "BartsParts lists Sparex 65870 as a metric radial shaft seal sized 29 x 40 x 8 mm.",
    },
    "6742-01-4580": {
        "Product Name": "Komatsu Seal - 6742-01-4580",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Komatsu",
        "Source Name": "Komatsu",
        "Source URL": "https://www.komatsu.com/en-us/products/parts/engine/6742-01-4580",
        "Evidence": "Komatsu lists 6742-01-4580 as an engine seal.",
    },
    "708-25-52861": {
        "Product Name": "Komatsu Oil Seal - 708-25-52861",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Komatsu",
        "Source Name": "US Replacement Parts",
        "Source URL": "https://www.usrparts.com/catalog/komatsu",
        "Evidence": "US Replacement Parts lists Komatsu 708-25-52861 as an oil seal.",
    },
    "11Y-30-14390": {
        "Product Name": "Komatsu Wiper Seal - 11Y-30-14390",
        "Product Family": "Hydraulic Seals",
        "Product Category": "Seals / Hydraulic Seals",
        "Manufacturer": "Komatsu",
        "Source Name": "Aztec Hydraulics",
        "Source URL": "https://aztechydraulics.com/products/kom-11y-30-14390",
        "Evidence": "Aztec Hydraulics lists Komatsu 11Y-30-14390 as a metric wiper seal.",
    },
    "17M-50-24360": {
        "Product Name": "Komatsu Seal - 17M-50-24360",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Komatsu",
        "Source Name": "Propel Parts",
        "Source URL": "https://propelparts.us/new4-17M-50-24360-Komatsu-Seal.html",
        "Evidence": "Propel Parts lists 17M-50-24360 / 17M5024360 as a Komatsu hydraulic seal.",
    },
    "17M5024360": {
        "Product Name": "Komatsu Seal - 17M-50-24360",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Komatsu",
        "Source Name": "Propel Parts",
        "Source URL": "https://propelparts.us/new4-17M-50-24360-Komatsu-Seal.html",
        "Evidence": "Propel Parts lists 17M-50-24360 / 17M5024360 as a Komatsu hydraulic seal.",
    },
    "9X4580": {
        "Product Name": "Caterpillar Seal Assembly - 9X4580",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Caterpillar",
        "Source Name": "Ring Power",
        "Source URL": "https://parts.ringpower.com/inventory/Part_Details?Model=D5H&PartGroup=Cabs&PartId=UCD&PartNumber=CAB-D5H-22F",
        "Evidence": "Ring Power lists Caterpillar 9X4580 as a seal assembly for D5H parts inventory.",
    },
    "119-5778": {
        "Product Name": "Hydraulic U-Cup Seal - 119-5778",
        "Product Family": "Hydraulic Seals",
        "Product Category": "Seals / Hydraulic Seals",
        "Manufacturer": "Caterpillar",
        "Source Name": "Cat Parts Store",
        "Source URL": "https://parts.cat.com/en/catcorp/119-5778",
        "Evidence": "Cat Parts lists 119-5778 as a backed U-cup seal.",
    },
    "1104-4547": {
        "Product Name": "Dust Seal - Steering Gear Sector",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Ford / New Holland",
        "Source Name": "S&R Tractor Service",
        "Source URL": "https://www.sharonandrobertractorservice.com/product-page/dust-seal-steering-gear-sector-also-used-as-brake-cross-shaft-dust-felt-seal",
        "Evidence": "S&R Tractor Service lists 1104-4547 as a steering gear sector dust seal / brake cross shaft dust felt seal.",
    },
    "2087073530": {
        "Product Name": "Komatsu Hydraulic Cylinder Seal - 208-70-73530",
        "Product Family": "Hydraulic Seals",
        "Product Category": "Seals / Hydraulic Seals",
        "Manufacturer": "Komatsu",
        "Source Name": "Propel Parts",
        "Source URL": "https://propelparts.us/new4-208-70-73530-Komatsu-Seal.html",
        "Evidence": "Propel Parts lists 208-70-73530 / 2087073530 as a Komatsu hydraulic cylinder seal.",
    },
    "R217611": {
        "Product Name": "King Pin Upper Seal - R217611",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "John Deere",
        "Source Name": "John Deere Shop",
        "Source URL": "https://shop.deere.com/us/product/R217611%3A-King-Pin-Upper-Seal/p/R217611",
        "Evidence": "John Deere lists R217611 as a king pin upper seal.",
    },
    "1850020M1": {
        "Product Name": "Steering Box Seal - 1850020M1",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Massey Ferguson",
        "Source Name": "Mian Autos",
        "Source URL": "https://mianautos.com/parts.php?categoryid=30&companyid=1&currentpage=6",
        "Evidence": "Mian Autos lists Massey Ferguson 1850020M1 as a steering seal.",
    },
    "1893623M1": {
        "Product Name": "Steering Box Seal - 1893623M1",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Massey Ferguson",
        "Source Name": "Massey Tractor Parts",
        "Source URL": "https://masseytractorparts.com/products/seal-1893623m1",
        "Evidence": "Massey Tractor Parts lists 1893623M1 as a Massey Ferguson seal for steering box applications.",
    },
    "6742-01-1520": {
        "Product Name": "Komatsu Liner Seal / O-Ring - 6742-01-1520",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Komatsu",
        "Source Name": "Komatsu",
        "Source URL": "https://www.komatsu.com/en-us/products/parts/engine/6742-01-1520",
        "Evidence": "Komatsu lists 6742-01-1520 as an engine seal; myKomatsu and Propel list it as a seal/O-ring.",
    },
    "50295": {
        "Product Name": "Metric Rotary Shaft Seal - 35 x 80 x 12 mm Double Lip",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Sparex",
        "Source Name": "Sparex",
        "Source URL": "https://gb.sparex.com/metric-rotary-shaft-seal-35-x-80-x-12mm-double-lip-50295.html",
        "Evidence": "Sparex lists S.50295 as a metric rotary shaft seal sized 35 x 80 x 12 mm double lip.",
    },
    "1A1120-61541": {
        "Product Name": "Rubber Seal - 1A1120-61541",
        "Product Family": "Oil Seals",
        "Product Category": "Seals / Oil Seals",
        "Manufacturer": "Yanmar",
        "Source Name": "Discount Equipment",
        "Source URL": "https://discount-equipment.com/product/441521-1a112061541-yanmar-seal-rubber/",
        "Evidence": "Discount Equipment lists Yanmar 1A1120-61541 as a rubber seal.",
    },
    "715500925": {
        "Product Name": "Komatsu Wear Ring - 07155-00925",
        "Product Family": "Hydraulic Seals",
        "Product Category": "Seals / Hydraulic Seals",
        "Manufacturer": "Komatsu",
        "Source Name": "Propel Parts",
        "Source URL": "https://propelparts.us/new4-07155-00925-Komatsu-Wear-Ring.html",
        "Evidence": "Propel Parts lists 07155-00925 with replacement part number 715500925 as a Komatsu wear ring.",
    },
    "RS3705": {
        "Product Name": "Inner Air Element - RS3705",
        "Product Family": "Air Filters",
        "Product Category": "Filters / Air Filters",
        "Manufacturer": "Baldwin",
        "Source Name": "Wheeler Fleet",
        "Source URL": "https://www.wheelerfleet.com/product/air-filter/900285",
        "Evidence": "Wheeler Fleet lists Baldwin RS3705 as a radial seal inner air element.",
    },
    "SBA131406370": {
        "Product Name": "Injector - SBA131406370",
        "Product Family": "Fuel System",
        "Product Category": "Fuel System",
        "Manufacturer": "New Holland",
        "Source Name": "New Holland Rochester",
        "Source URL": "https://www.newhollandrochester.com/shop/sba131406370/",
        "Evidence": "New Holland Rochester lists SBA131406370 as a New Holland injector.",
    },
    "RT100019A-WI": {
        "Product Name": "Rubber Track - RT100019A-WI",
        "Product Family": "Undercarriage",
        "Product Category": "Undercarriage",
        "Manufacturer": "John Deere",
        "Source Name": "Tornado Heavy Equipment Parts",
        "Source URL": "https://tornadoparts.com/products/takeuchi-excavator-tb153fr-rubber-tracks",
        "Evidence": "Tornado lists RT100019A-WI as a John Deere 50G compact excavator replacement rubber track.",
    },
    "VI8944762820": {
        "Product Name": "Turbo Exhaust Stud - 8944762820",
        "Product Family": "Hardware",
        "Product Category": "Hardware",
        "Manufacturer": "Isuzu",
        "Source Name": "FinditParts",
        "Source URL": "https://www.finditparts.com/products/9213236/isuzu-8944762820",
        "Evidence": "FinditParts lists Isuzu 8944762820 as a turbo exhaust stud.",
    },
    "8944762820": {
        "Product Name": "Turbo Exhaust Stud - 8944762820",
        "Product Family": "Hardware",
        "Product Category": "Hardware",
        "Manufacturer": "Isuzu",
        "Source Name": "FinditParts",
        "Source URL": "https://www.finditparts.com/products/9213236/isuzu-8944762820",
        "Evidence": "FinditParts lists Isuzu 8944762820 as a turbo exhaust stud.",
    },
    "YX12P01004P1": {
        "Product Name": "Muffler Clamp - YX12P01004P1",
        "Product Family": "Exhaust",
        "Product Category": "Engine / Exhaust",
        "Manufacturer": "Kobelco",
        "Source Name": "FridayParts",
        "Source URL": "https://www.fridayparts.com/muffler-clamp-yx12p01004p1-for-kobelco-sk135sr-sk135sr-1e-sk135srl-sk200sr-sk135srl-1e-sk200sr-1s-sk135srlc-sk200srlc-sk200srlc-1s-sk135srlc-1e",
        "Evidence": "FridayParts lists YX12P01004P1 as a Kobelco muffler clamp.",
    },
    "ZN18C08007": {
        "Product Name": "Hex Nut - M8 x 1.25",
        "Product Family": "Hardware",
        "Product Category": "Hardware",
        "Manufacturer": "CNH Industrial",
        "Source Name": "MyCNH Store",
        "Source URL": "https://www.mycnhstore.com/amea/en/caseih/cn/nut/p/ZN18C08007",
        "Evidence": "MyCNH lists ZN18C08007 as a nut sized M8 x 1.25.",
    },
    "ZN18C10008": {
        "Product Name": "Hex Nut - M10 x 1.50",
        "Product Family": "Hardware",
        "Product Category": "Hardware",
        "Manufacturer": "Kobelco / CNH Industrial",
        "Source Name": "MyCNH Store",
        "Source URL": "https://www.mycnhstore.com/eu/sv/casece/eu/light-equipment/mini-crawler-excavator/eues54min312cxb/mini-crawler-excavator-eu-asn-pu08-05000-asn-n7/section-1/cylinder-assy-swing/cn/5EFB7849-8FBF-E111-9FCE-005056875BD6/19DA6496-EFBE-E111-9FCE-005056875BD6",
        "Evidence": "MyCNH lists ZN18C10008 as a nut sized M10 x 1.50.",
    },
    "ZS18C10035": {
        "Product Name": "Hex Screw - M10 x 35 mm",
        "Product Family": "Hardware",
        "Product Category": "Hardware",
        "Manufacturer": "Kobelco",
        "Source Name": "Sealshydraulic",
        "Source URL": "https://www.sealshydraulic.com/sale-41592851-2438u1104r400-arm-cylinder-piston-rod-seal-kit-for-kobelco-sk200-sk210lc-sk200lc-sk210.html",
        "Evidence": "Kobelco cylinder parts listing shows ZS18C10035 as a hex screw M10 x 35 mm.",
    },
    "ZW16K08000": {
        "Product Name": "Washer - ZW16K08000",
        "Product Family": "Hardware",
        "Product Category": "Hardware",
        "Manufacturer": "CNH Industrial",
        "Source Name": "AGA Parts",
        "Source URL": "https://www.aga-parts.com/case-new-holland/part/zw16k08000_washer",
        "Evidence": "AGA Parts lists CNH Industrial ZW16K08000 as a washer.",
    },
    "ZW16X10000": {
        "Product Name": "Flat Washer - ZW16X10000",
        "Product Family": "Hardware",
        "Product Category": "Hardware",
        "Manufacturer": "CNH Industrial",
        "Source Name": "Messicks",
        "Source URL": "https://www.messicks.com/parts/new-holland/zw16x10000",
        "Evidence": "Messicks lists New Holland ZW16X10000 as a washer.",
    },
    "XFM-BC129-PL": {
        "Product Name": "Forestry Mulcher Reversible Planer Knife - XFM-BC129-PL",
        "Product Family": "Cutting Edges",
        "Product Category": "Ground Engaging Tools / Cutting Edges",
        "Manufacturer": "Xtreme Wear Parts",
        "Source Name": "Xtreme Wear Parts",
        "Source URL": "https://www.xtremewearparts.com/aftermarket-fits-bobcat-forestry-mulcher-teeth",
        "Evidence": "Xtreme Wear Parts lists XFM-BC129-PL as a reversible planer knife for Bobcat forestry mulcher teeth.",
    },
}


def read_csv(path):
    with path.open("r", newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def write_csv(path, rows, fields):
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows([
            {
                key: re.sub(r"\s+", " ", value).strip() if isinstance(value, str) else value
                for key, value in row.items()
            }
            for row in rows
        ])


def find_override(oem_value):
    raw = (oem_value or "").strip()
    if raw in OVERRIDES:
        return OVERRIDES[raw]
    parts = [part.strip() for part in raw.split(",")]
    for part in parts:
        if part in OVERRIDES:
            return OVERRIDES[part]
    raw_lower = raw.lower()
    if raw_lower in OVERRIDES:
        return OVERRIDES[raw_lower]
    for part in parts:
        if part.lower() in OVERRIDES:
            return OVERRIDES[part.lower()]
    for key, value in OVERRIDES.items():
        if key.lower() == raw_lower:
            return value
    for part in parts:
        part_lower = part.lower()
        for key, value in OVERRIDES.items():
            if key.lower() == part_lower:
                return value
    return None


def apply_to_master(path):
    rows = read_csv(path)
    changed = 0
    for row in rows:
        override = None
        for field in ["OEM Part Number", "Product Name", "Original Product Name", "Internal Reference"]:
            override = find_override(row.get(field, ""))
            if override:
                break
        if not override:
            continue
        original_notes = row.get("Notes", "").strip()
        row["Product Name"] = override["Product Name"]
        row["Product Family"] = override["Product Family"]
        row["Product Category"] = override["Product Category"]
        row["Manufacturer"] = override["Manufacturer"]
        row["Status"] = "Web Verified"
        row["Confidence"] = "0.95"
        row["Sales Description"] = override["Product Name"]
        row["Purchase Description"] = f"{override['Product Name']} | OEM: {row.get('OEM Part Number', '')}"
        row["Notes"] = "; ".join(x for x in [original_notes, f"web verified: {override['Source Name']}"] if x)
        keywords = row.get("Search Keywords", "")
        additions = [override["Product Name"], override["Manufacturer"]]
        for addition in additions:
            if addition and addition not in keywords:
                keywords = f"{keywords}; {addition}" if keywords else addition
        row["Search Keywords"] = keywords
        changed += 1
    write_csv(path, rows, rows[0].keys())
    return changed


def apply_to_review(path):
    rows = read_csv(path)
    remaining = [
        row for row in rows
        if not find_override(row.get("OEM Part Number", ""))
    ]
    fields = rows[0].keys() if rows else [
        "Row Number", "Internal Reference", "OEM Part Number", "Original Name",
        "Suggested Name", "Suggested Category", "Product Family", "Reason",
        "Confidence", "Notes",
    ]
    write_csv(path, remaining, fields)
    return len(rows) - len(remaining)


def write_sources(path):
    fields = [
        "OEM Part Number", "Verified Product Name", "Product Family",
        "Product Category", "Manufacturer", "Source Name", "Source URL",
        "Evidence",
    ]
    rows = []
    for oem, data in OVERRIDES.items():
        rows.append({
            "OEM Part Number": oem,
            "Verified Product Name": data["Product Name"],
            "Product Family": data["Product Family"],
            "Product Category": data["Product Category"],
            "Manufacturer": data["Manufacturer"],
            "Source Name": data["Source Name"],
            "Source URL": data["Source URL"],
            "Evidence": data["Evidence"],
        })
    write_csv(path, rows, fields)


def main():
    master_changed = sum(apply_to_master(path) for path in MASTER_PATHS if path.exists())
    review_changed = sum(apply_to_review(path) for path in REVIEW_PATHS if path.exists())
    for path in SOURCE_PATHS:
        path.parent.mkdir(parents=True, exist_ok=True)
        write_sources(path)
    print(f"Master rows web-updated across files: {master_changed}")
    print(f"Needs-review rows removed across files: {review_changed}")
    print(f"Web source rows written: {len(OVERRIDES)}")


if __name__ == "__main__":
    main()
