{
    "name": "Southern Service",
    "version": "19.0.1.18.0",
    "author": "Southern Equipment",
    "category": "Services",
    "summary": "One Service workflow across Sales, customer equipment, field work, shop work, maintenance, and purchasing.",
    "depends": [
        "mail",
        "sale_management",
        "sale_stock",
        "sale_purchase",
        "industry_fsm",
        "industry_fsm_sale",
        "industry_fsm_stock",
        "repair",
        "purchase",
        "purchase_stock",
        "purchase_repair",
        "maintenance",
        "cs_client_equipment",
        "dmc_fieldservice",
    ],
    "data": [
        "security/service_security.xml",
        "security/ir.model.access.csv",
        "data/service_sequence.xml",
        "views/res_config_settings_views.xml",
        "views/service_ai_suggestion_views.xml",
        "views/service_case_views.xml",
        "views/sale_order_views.xml",
        "views/project_task_views.xml",
        "views/service_inspection_views.xml",
        "views/repair_order_views.xml",
        "views/maintenance_views.xml",
        "views/purchase_order_views.xml",
        "views/client_equipment_views.xml",
        "views/service_menus.xml",
    ],
    "application": True,
    "installable": True,
    "license": "LGPL-3",
}
